@echo off
REM BrasilIntel Automated Run Template
REM This file is a template - actual batch files are generated by setup_scheduled_task.ps1
REM
REM Usage: This script template shows the structure used for scheduled tasks.
REM        The setup script will create category-specific batch files:
REM        - run_health.bat
REM        - run_dental.bat
REM        - run_group_life.bat

REM Get the directory where this script is located
SET SCRIPT_DIR=%~dp0
cd /d "%SCRIPT_DIR%\.."

REM Generate timestamp for log file
for /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
for /f "tokens=1-2 delims=/: " %%a in ('time /t') do (set mytime=%%a%%b)
set timestamp=%mydate%_%mytime%

REM Activate virtual environment
call venv\Scripts\activate.bat

REM Run BrasilIntel with specified category
REM Replace {category} with actual category: health, dental, or group_life
echo Running BrasilIntel for category: {category} >> "data\logs\{category}_%mydate%.log"
python -m app.main run --category {category} >> "data\logs\{category}_%mydate%.log" 2>&1

REM Capture and log exit code
set exitcode=%errorlevel%
echo Exit code: %exitcode% >> "data\logs\{category}_%mydate%.log"
echo. >> "data\logs\{category}_%mydate%.log"

REM Exit with the same code as the Python script
exit /b %exitcode%
