<#
.SYNOPSIS
    Sets up Windows Scheduled Tasks for BrasilIntel automated runs.

.DESCRIPTION
    Creates scheduled tasks for daily execution of BrasilIntel competitive intelligence runs.
    Each category runs at a specific time: Health (6 AM), Dental (7 AM), Group Life (8 AM).

.PARAMETER AppPath
    Path to BrasilIntel application directory (default: script location parent)

.PARAMETER TaskNamePrefix
    Prefix for scheduled task names (default: BrasilIntel)

.PARAMETER Category
    Category to setup: health, dental, group_life, or all (default: all)

.PARAMETER RunNow
    If specified, runs the tasks immediately after creation

.EXAMPLE
    .\setup_scheduled_task.ps1
    Sets up all scheduled tasks

.EXAMPLE
    .\setup_scheduled_task.ps1 -Category health -RunNow
    Sets up health category task and runs it immediately
#>

param(
    [string]$AppPath = (Split-Path -Parent $PSScriptRoot),
    [string]$TaskNamePrefix = "BrasilIntel",
    [ValidateSet("health", "dental", "group_life", "all")]
    [string]$Category = "all",
    [switch]$RunNow
)

# Requires administrator privileges
#Requires -RunAsAdministrator

Write-Host "=== BrasilIntel Scheduled Task Setup ===" -ForegroundColor Cyan
Write-Host ""

# Verify app path exists
if (-not (Test-Path $AppPath)) {
    Write-Host "ERROR: Application path not found: $AppPath" -ForegroundColor Red
    exit 1
}

Write-Host "Application path: $AppPath" -ForegroundColor Green

# Verify virtual environment exists
$VenvPath = Join-Path $AppPath "venv"
if (-not (Test-Path $VenvPath)) {
    Write-Host "ERROR: Virtual environment not found: $VenvPath" -ForegroundColor Red
    Write-Host "Please run: python -m venv venv" -ForegroundColor Yellow
    exit 1
}

Write-Host "Virtual environment: $VenvPath" -ForegroundColor Green

# Verify .env file exists
$EnvFile = Join-Path $AppPath ".env"
if (-not (Test-Path $EnvFile)) {
    Write-Host "ERROR: .env file not found: $EnvFile" -ForegroundColor Red
    Write-Host "Please create .env file with required configuration" -ForegroundColor Yellow
    exit 1
}

Write-Host "Environment file: $EnvFile" -ForegroundColor Green
Write-Host "Server port: Configured in .env (default: 8000)" -ForegroundColor Green

# Create logs directory
$LogsPath = Join-Path $AppPath "data\logs"
if (-not (Test-Path $LogsPath)) {
    New-Item -ItemType Directory -Path $LogsPath -Force | Out-Null
    Write-Host "Created logs directory: $LogsPath" -ForegroundColor Green
} else {
    Write-Host "Logs directory exists: $LogsPath" -ForegroundColor Green
}

Write-Host ""

# Define schedules for each category
$Schedules = @{
    "health" = @{
        Time = "06:00"
        Description = "Daily health insurance competitive intelligence run"
    }
    "dental" = @{
        Time = "07:00"
        Description = "Daily dental insurance competitive intelligence run"
    }
    "group_life" = @{
        Time = "08:00"
        Description = "Daily group life insurance competitive intelligence run"
    }
}

# Determine which categories to process
$CategoriesToProcess = if ($Category -eq "all") {
    @("health", "dental", "group_life")
} else {
    @($Category)
}

# Create scheduled tasks for each category
foreach ($Cat in $CategoriesToProcess) {
    Write-Host "Setting up task for category: $Cat" -ForegroundColor Cyan

    $TaskName = "${TaskNamePrefix}_${Cat}"
    $Schedule = $Schedules[$Cat]

    # Create batch script for this category
    $BatchFile = Join-Path $AppPath "deploy\run_${Cat}.bat"
    $BatchContent = @"
@echo off
REM BrasilIntel Automated Run - $Cat
REM Generated by setup_scheduled_task.ps1

cd /d "$AppPath"

REM Generate timestamp for log file
for /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
for /f "tokens=1-2 delims=/: " %%a in ('time /t') do (set mytime=%%a%%b)
set timestamp=%mydate%_%mytime%

REM Activate virtual environment and run
REM Port is read from .env file by the application
call venv\Scripts\activate.bat
echo Running BrasilIntel for category: $Cat >> "data\logs\${Cat}_%mydate%.log"
python -m app.main run --category $Cat >> "data\logs\${Cat}_%mydate%.log" 2>&1

REM Capture exit code
set exitcode=%errorlevel%
echo Exit code: %exitcode% >> "data\logs\${Cat}_%mydate%.log"
exit /b %exitcode%
"@

    Set-Content -Path $BatchFile -Value $BatchContent -Encoding UTF8
    Write-Host "  Created batch script: $BatchFile" -ForegroundColor Green

    # Remove existing task if it exists
    $ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($ExistingTask) {
        Write-Host "  Removing existing task: $TaskName" -ForegroundColor Yellow
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }

    # Create scheduled task action
    $Action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$BatchFile`""

    # Create daily trigger at specified time
    $Trigger = New-ScheduledTaskTrigger -Daily -At $Schedule.Time

    # Configure task settings
    $Settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 3 `
        -RestartInterval (New-TimeSpan -Minutes 5)

    # Create principal (run as SYSTEM account)
    $Principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

    # Register the scheduled task
    $Task = Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $Action `
        -Trigger $Trigger `
        -Settings $Settings `
        -Principal $Principal `
        -Description $Schedule.Description

    Write-Host "  Created scheduled task: $TaskName" -ForegroundColor Green
    Write-Host "  Schedule: Daily at $($Schedule.Time)" -ForegroundColor Green

    # Run now if requested
    if ($RunNow) {
        Write-Host "  Starting task immediately..." -ForegroundColor Yellow
        Start-ScheduledTask -TaskName $TaskName
        Write-Host "  Task started" -ForegroundColor Green
    }

    Write-Host ""
}

Write-Host "=== Setup Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Management Commands:" -ForegroundColor Yellow
Write-Host "  Run now:    .\deploy\manage_service.ps1 -Action run-now -Category <category>" -ForegroundColor White
Write-Host "  Start:      .\deploy\manage_service.ps1 -Action start -Category <category>" -ForegroundColor White
Write-Host "  Stop:       .\deploy\manage_service.ps1 -Action stop -Category <category>" -ForegroundColor White
Write-Host "  Status:     .\deploy\manage_service.ps1 -Action status" -ForegroundColor White
Write-Host "  Logs:       .\deploy\manage_service.ps1 -Action logs -Category <category>" -ForegroundColor White
Write-Host "  Remove:     .\deploy\manage_service.ps1 -Action remove" -ForegroundColor White
Write-Host ""
